version: '2.1'
services:

   inventory:
      image: "{{ nexus_docker_repo }}/onap/org.onap.dcaegen2.platform.inventory-api:{{ dcae_docker_inv }}"
      restart: "always"
      container_name: "inventory"
      hostname: "inventory"
      environment:
       - "POSTGRES_USER=inventory"
       - "POSTGRES_PASSWORD=inventorypwd"
      ports:
       - "8080:8080"
      labels:
       - "SERVICE_8080_NAME=inventory"
       - "SERVICE_8080_CHECK_HTTP=/dcae-service-types"
       - "SERVICE_8080_CHECK_INTERVAL=15s"
       - "SERVICE_8080_CHECK_INITIAL_STATUS=passing"
      volumes:
       - ./tls/shared:/opt/tls/shared


   service-change-handler:
      image: "{{ nexus_docker_repo }}/onap/org.onap.dcaegen2.platform.servicechange-handler:{{ dcae_docker_sch }}"
      container_name: "service-change-handler"
      restart: "always"
      hostname: "service-change-handler"
      ports:
       - "8079:8079"
      environment:
       - "POSTGRES_USER=inventory"
       - "POSTGRES_PASSWORD=inventorypwd"
      labels:
       - "SERVICE_NAME=service_change_handler"
       - "SERVICE_CHECK_DOCKER_SCRIPT=/opt/health.sh"
       - "SERVICE_CHECK_INTERVAL=15s"
       - "SERVICE_CHECK_INITIAL_STATUS=passing"
      volumes:
       - ./tls/shared:/opt/tls/shared


   deployment_handler:
      image: "{{ nexus_docker_repo }}/onap/org.onap.dcaegen2.platform.deployment-handler:{{ dcae_docker_dh }}"
      container_name: "deployment-handler"
      restart: "always"
      hostname: "deployment-handler"
      environment:
       - "CLOUDIFY_PASSWORD=admin"
       - "CLOUDIFY_USER=admin"
      ports:
       - "8188:8443"
      labels:
       - "SERVICE_8443_NAME=deployment_handler"
       - "SERVICE_8443_CHECK_HTTP=/"
       - "SERVICE_8443_CHECK_INTERVAL=15s"
       - "SERVICE_8443_CHECK_INITIAL_STATUS=passing"
      volumes:
       - ./tls/shared:/opt/tls/shared


   policy_handler:
      image: "{{ nexus_docker_repo }}/onap/org.onap.dcaegen2.platform.policy-handler:{{ dcae_docker_ph }}"
      container_name: "policy-handler"
      restart: "always"
      hostname: "policy-handler"
      ports:
       - "25577:25577"
      labels:
       - "SERVICE_25577_NAME=policy_handler"
       - "SERVICE_25577_CHECK_HTTP=/healthcheck"
       - "SERVICE_25577_CHECK_INTERVAL=15s"
       - "SERVICE_25577_CHECK_INITIAL_STATUS=passing"
      volumes:
       - ./tls/shared:/opt/tls/shared

