version: '2.1'
services:

   mvp-dcaegen2-collectors-ves:
      image: "{{ nexus_docker_repo }}/onap/org.onap.dcaegen2.collectors.ves.vescollector:{{ dcae_docker_ves }}"
      container_name: "mvp-dcaegen2-collectors-ves"
      restart: "always"
      hostname: "mvp-dcaegen2-collectors-ves"
      environment:
       - "DMAAPHOST={{ mr_ip_addr }}"
       - "CONSUL_HOST=consul"
       - "CONSUL_PORT=8500"
       - "CONFIG_BINDING_SERVICE=config_binding_service"
       - "SERVICE_NAME=mvp-dcaegen2-collectors-ves"
       - "HOSTNAME=mvp-dcaegen2-collectors-ves"
      ports:
       - "8081:8080"
      labels:
       - "SERVICE_8080_NAME=mvp-dcaegen2-collectors-ves"
       - "SERVICE_8080_CHECK_HTTP=/healthcheck"
       - "SERVICE_8080_CHECK_INTERVAL=15s"
       - "SERVICE_8080_CHECK_INITIAL_STATUS=passing"


   mvp-dcaegen2-analytics-tca:
      image: "{{ nexus_docker_repo }}/onap/org.onap.dcaegen2.deployments.tca-cdap-container:{{ dcae_docker_tca }}"
      container_name: "mvp-dcaegen2-analytics-tca"
      restart: "always"
      hostname: "mvp-dcaegen2-analytics-tca"
      environment:
       - "DMAAPHOST={{ mr_ip_addr }}"
       - "DMAAPPORT=3904"
       - "DMAAPPUBTOPIC=unauthenticated.DCAE_CL_OUTPUT"
       - "DMAAPSUBTOPIC=unauthenticated.VES_MEASUREMENT_OUTPUT"
       - "AAIHOST={{ aai1_ip_addr }}"
       - "AAIPORT=8443"
       - "CONSUL_HOST=consul"
       - "CONSUL_PORT=8500"
       - "CBS_HOST=config-binding-service"
       - "CBS_PORT=10000"
       - "SERVICE_NAME=mvp-dcaegen2-analytics-tca"
       - "HOSTNAME=mvp-dcaegen2-analytics-tca"
       - "CONFIG_BINDING_SERVICE=config_binding_service"
       # set the parameter below to enable REDIS caching. 
       #- REDISHOSTPORT=redis-cluster:6379
      ports:
       - "11011:11011"
       #- "11015:11015"
      labels:
       - "SERVICE_11011_NAME=mvp-dcaegen2-analytics-tca"
       - "SERVICE_11011_CHECK_HTTP=/cdap/ns/cdap_tca_hi_lo"
       - "SERVICE_11011_CHECK_INTERVAL=15s"
       - "SERVICE_11011_CHECK_INITIAL_STATUS=passing"

   mvp-dcaegen2-analytics-holmes-engine-management:
      image: "{{ nexus_docker_repo }}/onap/holmes/engine-management:{{ holmes_docker_em }}"
      container_name: "mvp-dcaegen2-analytics-holmes-engine-management"
      restart: "always"
      hostname: "mvp-dcaegen2-analytics-holmes-engine-management"
      environment:
       - "URL_JDBC=pgHolmes:5432"
       - "JDBC_USERNAME=holmes"
       - "JDBC_PASSWORD=holmespwd"
       - "MSB_ADDR={{ msb_ip_addr }}"
       - "CONSUL_HOST=consul"
       - "CONSUL_PORT=8500"
       - "CONFIG_BINDING_SERVICE=config_binding_service"
       - "HOSTNAME=mvp-dcaegen2-analytics-holmes-engine-management"
      ports:
       - "9102:9102"
      labels:
       - "SERVICE_9102_IGNORE=true"

   mvp-dcaegen2-analytics-holmes-rule-management:
      image: "{{ nexus_docker_repo }}/onap/holmes/rule-management:{{ holmes_docker_rm }}"
      container_name: "mvp-dcaegen2-analytics-holmes-rule-management"
      restart: "always"
      hostname: "mvp-dcaegen2-analytics-holmes-rule-management"
      environment:
       - "URL_JDBC=pgHolmes:5432"
       - "JDBC_USERNAME=holmes"
       - "JDBC_PASSWORD=holmespwd"
       - "MSB_ADDR={{ msb_ip_addr }}"
       - "CONSUL_HOST=consul"
       - "CONSUL_PORT=8500"
       - "CONFIG_BINDING_SERVICE=config_binding_service"
       - "HOSTNAME=mvp-dcaegen2-analytics-holmes-rule-management"
      ports:
       - "9101:9101"
      labels:
       - "SERVICE_9101_IGNORE=true"

